### ISSUE TITLE
Req: rpc-user and rpc-passwd support

### ISSUE THREAD

**Issue by pepa65** [baskerville/diana#7]
My server has aria2 1.18.1 which doesn't support RPC-SECRET.
Would it be possible to support RPC-USER and RPC-PASSWD alternatively as well? (I tried hacking it in, but wasn't successful...)

**Comment by baskerville** [comment]
Unfortunately, the `--rpc-user` option is going to be deprecated.

Can't you install aria2 locally?

**Comment by pepa65** [comment]
Local system is actually also on Ubuntu 14.04 LTS. But it compiled well, and somehow it seems I can just copy the binary (although it is 77MB!! even with ARIA2_STATIC=no) and use it on the server.
On the other hand, many (sensible) people will be on Ubuntu LTS for another year if not longer, so if it is not too hard to build it in, it might attract more users.

**Comment by baskerville** [comment]
Added via 8f70c4d.
Example:
```
dad -u USERNAME -p PASSWORD
diana -u USERNAME -p PASSWORD stats
```

**Comment by pepa65** [comment]
Cool thanks!
